# These are supported funding model platforms

github: [lepture]
patreon: lepture
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/Authlib
custom: https://lepture.com/donate
