version: "2"
checks:
  argument-count:
    enabled: false

  method-complexity:
    enabled: true
    config:
      threshold: 10

  method-lines:
    enabled: true
    config:
      threshold: 35

  method-count:
    enabled: false

  file-lines:
    config:
      threshold: 460

  return-statements:
    config:
      threshold: 6

  similar-code:
    enabled: false

  identical-code:
    enabled: true
    config:
      threshold: 100
